version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      golang-x:
        patterns:
          - golang.org/x/*
  - package-ecosystem: docker
    directory: .buildkite
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
