FROM golang:1.25.4@sha256:6ca9eb0b32a4bd4e8c98a4a2edf2d7c96f3ea6db6eb4fc254eef6c067cf73bb4

COPY --from=golangci/golangci-lint:v2.5.0@sha256:0c8e590120a98ada5d0d9423e65dd957067e70c87efd692e83d5a311ddfc3151 /usr/bin/golangci-lint /usr/local/bin/golangci-lint

# install aws-cli
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/cache/debconf \
    --mount=type=cache,target=/var/lib/apt \
    export ARCH=$(uname -m) \
    && apt-get update \
    && apt-get install -y --no-install-recommends unzip zip bash jq curl git lsb-release openssh-client \
    && curl https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip -o /tmp/awscliv2.zip \
    && unzip -q /tmp/awscliv2.zip -d /opt \
    && /opt/aws/install --update -i /usr/local/aws-cli -b /usr/local/bin \
    && rm -rf /tmp/awscliv2.zip /opt/aws \
    && aws --version
